// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementSystem.Data;

#nullable disable

namespace StudentManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930004406_DataSeeding")]
    partial class DataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagementSystem.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Courses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Course_Credits", "Credits > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Credits = 3,
                            Description = "Fundamentals of C# programming and OOP.",
                            Title = "C# Fundamentals"
                        },
                        new
                        {
                            Id = 102,
                            Credits = 3,
                            Description = "Relational databases and SQL Server.",
                            Title = "SQL Server"
                        },
                        new
                        {
                            Id = 103,
                            Credits = 4,
                            Description = "Entity Framework Core and database operations.",
                            Title = "EF Core"
                        },
                        new
                        {
                            Id = 104,
                            Credits = 3,
                            Description = "Building backend applications using ASP.NET Core.",
                            Title = "ASP.NET Core"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.CourseInstructor", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CourseId", "InstructorId");

                    b.HasIndex("InstructorId");

                    b.ToTable("CourseInstructors", (string)null);

                    b.HasData(
                        new
                        {
                            CourseId = 101,
                            InstructorId = 1,
                            Role = "Main Instructor"
                        },
                        new
                        {
                            CourseId = 102,
                            InstructorId = 2,
                            Role = "Main Instructor"
                        },
                        new
                        {
                            CourseId = 103,
                            InstructorId = 1,
                            Role = "Main Instructor"
                        },
                        new
                        {
                            CourseId = 104,
                            InstructorId = 1,
                            Role = "Lead Instructor"
                        },
                        new
                        {
                            CourseId = 104,
                            InstructorId = 3,
                            Role = "Assistant Instructor"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Enrollment", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Enrollments", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CourseId = 101,
                            EnrollmentDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 85
                        },
                        new
                        {
                            StudentId = 1,
                            CourseId = 102,
                            EnrollmentDate = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 90
                        },
                        new
                        {
                            StudentId = 1,
                            CourseId = 103,
                            EnrollmentDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 95
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 101,
                            EnrollmentDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 75
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 102,
                            EnrollmentDate = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 101,
                            EnrollmentDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 95
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 103,
                            EnrollmentDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 88
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 102,
                            EnrollmentDate = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 70
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 103,
                            EnrollmentDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 92
                        },
                        new
                        {
                            StudentId = 5,
                            CourseId = 101,
                            EnrollmentDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 65
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"));

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InstructorId");

                    b.ToTable("Instructors", (string)null);

                    b.HasData(
                        new
                        {
                            InstructorId = 1,
                            FName = "Mohamed",
                            LName = "Hassan"
                        },
                        new
                        {
                            InstructorId = 2,
                            FName = "Ahmed",
                            LName = "Ali"
                        },
                        new
                        {
                            InstructorId = 3,
                            FName = "Sara",
                            LName = "Mohamed"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Email = "ahmed.adel@test.com",
                            EnrollmentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FName = "Ahmed",
                            IsDeleted = false,
                            LName = "Adel"
                        },
                        new
                        {
                            StudentId = 2,
                            Email = "ahmed.hassan@test.com",
                            EnrollmentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FName = "Ahmed",
                            IsDeleted = false,
                            LName = "Hassan"
                        },
                        new
                        {
                            StudentId = 3,
                            Email = "omar.mohamed@test.com",
                            EnrollmentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FName = "Omar",
                            IsDeleted = false,
                            LName = "Mohamed"
                        },
                        new
                        {
                            StudentId = 4,
                            Email = "sara.ali@test.com",
                            EnrollmentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FName = "Sara",
                            IsDeleted = false,
                            LName = "Ali"
                        },
                        new
                        {
                            StudentId = 5,
                            Email = "youssef.samir@test.com",
                            EnrollmentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FName = "Youssef",
                            IsDeleted = false,
                            LName = "Samir"
                        },
                        new
                        {
                            StudentId = 6,
                            Email = "deleted.student@test.com",
                            EnrollmentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FName = "Deleted",
                            IsDeleted = true,
                            LName = "Student"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.CourseInstructor", b =>
                {
                    b.HasOne("StudentManagementSystem.Entities.Course", "Course")
                        .WithMany("CourseInstructors")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Entities.Instructor", "Instructor")
                        .WithMany("CourseInstructors")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Enrollment", b =>
                {
                    b.HasOne("StudentManagementSystem.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Course", b =>
                {
                    b.Navigation("CourseInstructors");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Instructor", b =>
                {
                    b.Navigation("CourseInstructors");
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
